SECTION="NetPing modules"
CATEGORY="Base"
TITLE="EPIC OWRT-PLIB-ubus"

PKG_NAME="OWRT-PLIB-ubus"
PKG_VERSION="0.1.1-1"
PKG_RELEASE=1

LIB_DIR=/usr/lib/python3.7/lib-dynload
LIB=ubus.cpython-37.so

.PHONY: all install

all: install

install:
	mkdir -p $(LIB_DIR)
	for f in $(LIB); do cp -r $${f} $(LIB_DIR); done

clean:
	for f in $(LIB); do rm -f $(LIB_DIR)$${f}; done
